Feature/jwt authenticator
halloverden/symfony-jwt-authenticator-bundle pull request #2
Opened 2022-07-06 15:47 UTC by tomme87

Adds the JWT authenticator.

This is step 2 of 3 before first release.

depends on #1

2022-07-06 20:11 UTC, tomme87 commented on src/Security/Authenticator/JwtAuthenticator.php
> +    $jwt = $this->jwtService->parseAndVerify($token);
Might need to move this to `supports`

2022-07-08 14:17 UTC, erichjsonfosse requested changes

2022-07-08 14:17 UTC, erichjsonfosse commented on src/Security/Authenticator/JwtAuthenticator.php
> +    $errorMessage = \strtr($exception->getMessageKey(), $exception->getMessageData());
Might be a good idea. Could we check for the existence of a given translator key, maybe?

2022-07-08 14:27 UTC, tomme87 commented on src/Security/Authenticator/JwtAuthenticator.php
> +    $errorMessage = \strtr($exception->getMessageKey(), $exception->getMessageData());
The `messageKey` is the translator key. here is how other authenticators use it:

```php
if (null !== $this->translator) {
  $errorMessage = $this->translator->trans($exception->getMessageKey(), $exception->getMessageData(), 'security');
} else {
  $errorMessage = strtr($exception->getMessageKey(), $exception->getMessageData());
}
```

2022-07-08 14:55 UTC, erichjsonfosse approved these changes

2022-07-08 16:41 UTC, merged